### ISSUE TITLE
Online Oткрытые позиции по фьючерсам

### ISSUE THREAD

**Issue by KonstantinReim** [Kataane/Fiss#6]
Здравствуйте, есть ли возможность с помощью Вашей библиотеки получать Online Oткрытые позиции по фьючерсам? Пробую по разному пока не получается. [https://www.moex.com/ru/derivatives/open-positions-online.aspx](url) [https://www.moex.com/ru/analyticalproducts?futoi](url)

**Comment by Kataane** [comment]
Добрый

**Comment by Kataane** [comment]
Добрый день. 
Следуя данному [документу](https://fs.moex.com/f/12741/get-futoi-data.pdf). Данные по всем доступным контрактам, доступны только после регистрации и оформления подписки.
На данный момент, библиотека не располагает возможностями авторизации через [паспорт](https://passport.moex.com/authenticate).

В текущий момент, данная библиотека еще находится в процессе развития и становления. Я добавлю Ваше пожелания в следующие версии библиотеки.

После того, как будет добавлена авторизация через паспорт, Вы сможете запрашивать данные по фьючерсам, следующим образом:
```csharp
var request = new IssRequest();
request.AnalyticalProducts().Futoi().Securities("si");
```

**Comment by Kataane** [comment]
Открыл [issue ](https://github.com/Kataane/Fiss/issues/7)

**Comment by KonstantinReim** [comment]
Спасибо.
