### ISSUE TITLE
Авторизация через паспорт MOEX

### ISSUE THREAD

**Issue by Kataane** [Kataane/Fiss#7]
Необходимо реализовать авторизацию через паспорт MOEX, для получения доступа к данным, которые требуют подписку или авторизации пользователя.

Для реализации авторизации необходимо следующее:

- [ ]  Отправка login и password в следующий запрос: https://passport.moex.com/authenticate
- [ ]  Получение cookies = {'MicexPassportCert': s.cookies['MicexPassportCert']}
- [ ]  Отправка запроса требующего авторизацию со следующими параметрами: req = re.get(url, headers=headers, cookies = cookies)

Пример реализации описан в следующем [документе ](https://fs.moex.com/f/12741/get-futoi-data.pdf) от MOEX

**Comment by KonstantinReim** [comment]
Приветствую, как успехи по Авторизация через паспорт MOEX?

**Comment by Kataane** [comment]
Добрый день. 

Пока авторизация через паспорт MOEX не запланирована на будущие итерации разработки, так как требуется провести работу по оптимизации процесса, начиная от построения запроса до получения данных, чтобы гарантировать, что система готова к будущим изменениям. Текущая реализация - это прототип, который разрабатывался в свободное время.

Учитывая, что проект является личной инициативой, я не могу предоставить точный график завершения этой работы. Однако, как только авторизация через паспорт MOEX будет добавлена в новую версию библиотеки, я сразу же сообщу вам об этом.

Если у Вас есть дополнительные вопросы, пожалуйста, не стесняйтесь задавать их.

**Comment by KonstantinReim** [comment]
Спасибо!

**Comment by Kataane** [comment]
@KonstantinReim 

Добрый день. По Вашей просьбе добавлен в тестовом режиме клиент, для аутентификации на Passport MOEX и получения данных, требующие авторизацию.

Доступ пока можно, только получить установив библиотеку локально. В течение нескольких недель, будет выпущен отдельный пакет-расширение.

Подробно о том как пользоваться клиентом, написано в [Readme.md](https://github.com/Kataane/Fiss/blob/future/rework/Readme.md), в главе Passport MOEX.

Буду очень признателен, если Вы найдете время протестировать клиент до публикации пакета-расширения и оставить отзывы, чтобы я смог улучшить и сделать его идеальным для дальнейшего использования.

Если у Вас есть дополнительные вопросы, пожалуйста, не стесняйтесь задавать их.

**Comment by KonstantinReim** [comment]
Спасибо за оперативность и отзывчивость. Протестировать в ближайшее время пока не смогу, но обязательно этим займусь чуть позже.
